### ISSUE TITLE
Cant install with python 3.6.1 on Windows 10 64bit

### ISSUE THREAD

**Issue by Garztone** [mhammond/pywin32#1120]
when i run "pywin32/setup3.py" install
i get Traceback (most recent call last):
line 16, in <module>
exec(str(got))
File "<string>", line 1944, in <module>
File "<string>", line 594, in __init__
Path: -venvs\tt\lib\ntpath.py", line 75, in join
path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by thopiekar** [comment]
I used the installers from here: https://sourceforge.net/projects/pywin32/files/pywin32/Build%20221/
For me it worked without issues.

**Comment by labrys** [comment]
Essentially same issue installing with 2.7.14:
```

**Comment by mhammond** [comment]
setup.py is used to build pywin32 from scratch and requires a number of tools, including Visual Studio compilers and Windows SDKs to be installed. The error you are seeing is setup.py not finding the SDK directories. I've changed setup.py in 4b734a86 to throw with a better message in this case instead of the obscure behaviour you saw
