### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by gbear605** [mhammond/pywin32#1142]
I'm trying to run Python code that imports `win32com.client`. I installed a clean install of Python 3.6.4 and pywin32-221.win32-py3.6.exe.

I'm on 32 bit Window 10.

When I tried to run my code from IDLE, it gave the following traceback:

```
Traceback (most recent call last):
  File "C:\Users\gbear605\Downloads\StarShoot.py", line 4, in <module>
    import win32com.client
  File "C:\Users\gbear605\AppData\Local\Programs\Python\Python36-32\lib\site-packages\win32com\__init__.py", line 5, in <module>
    import win32api, sys, os
ImportError: DLL load failed: The specified module could not be found.
```

I noticed that in File Explorer, there was also an option for "Edit with Pythonwin" when I right-clicked on my Python source file, so I tried that. It errors by saying that it is missing "VCRUNTIME140.dll," so I installed the [Visual C++ Redistributable Packages](https://www.microsoft.com/en-us/download/details.aspx?id=48145). After installing that, I get the same traceback in IDLE but Pythonwin now errors with "Still can't get my hands on win32ui."

_However_, if I directly open Pythonwin and then run the file, it works fine.

**Comment by Avasam** [comment]
Since 71afa71e11e6631be611ca5cb57cda526b5e91ab, the `PATH` is now prepended, rather than appended. For Python >= 3.8, the `PATH` environment variable isn't even used. This is included in pywin32==226.

Python 3.7 has also reached EOL (meaning no security fixes/support) and I'd recommend migrating over to 3.8+ (see #2207)

[.exe installers are now deprecated](https://github.com/mhammond/pywin32#binaries) #1939, so you should install from PyPI (ie: `pip install pywin32>=226`)

Given the sheer amount of "ImportError: DLL load failed: The specified module could not be found." issue duplication and old history, I'd like to consolidate the current state of these issues. So I'll close and reference back any issue that only has comments showing the issue:
- from before November 10th, 2019 (pywin32<226)
- using `.exe` installers
- using Python < 3.8

Please also try https://github.com/mhammond/pywin32#troubleshooting before opening a new issue, or let us, and others, know if it **did** resolve your issue.
