### ISSUE TITLE
pypiwin32 223 permission issues

### ISSUE THREAD

**Issue by tardyp** [mhammond/pywin32#1171]
Looks like new version brakes in appveyor:

https://ci.appveyor.com/project/djmitche/buildbot/build/1.0.5999
for all version of python.

Error is:
```
IOError: [Errno 13] Permission denied: 'C:\\Python27\\Lib\\site-packages\\pywin32_system32\\pythoncom27.dll'
```

**Comment by xoviat** [comment]
Duplicate pypa/pip#4874. 

I submitted buildbot/buildbot#3974 to resolve the issue.

**Comment by xoviat** [comment]
I've confirmed that the PR resolves the issue. As this is not our fault, closing.

Note: I share your frustration with the slow pace of pip development (which has not had a release for over a year now I think). I have tried to resolve the problem, but the people in charge of that project have foreclosed all possibilities to resolving the situation.

cc @pfmoore

**Comment by tardyp** [comment]
@xoviat I think for the sanity of our users, we can't require them to install git version of pip.
So I kindly suggest to stick with pypiwin32 <222 for the wheels.

This is not only for buildbot's Appveyor CI, I expect to get lot of support request because people get confused by pywin32 not working with a standard pip install.

**Comment by xoviat** [comment]
I would hope to see a bugfix release of pip soon. As far as "working with a standard pip install", the bug only appears when pip is uninstalling an existing version.

**Comment by xoviat** [comment]
If you unpin the pypiwin32 version [here](https://ci.appveyor.com/project/djmitche/buildbot/build/1.0.6006/job/1qvr6aq0oiitklia#L283), pip won't install the existing version, and thus should succeed.

**Comment by tardyp** [comment]
@xoviat looks like this pinning comes from https://github.com/docker/docker-py/commit/a5490ad0be6840961758d090f573ceb1ef0a5d96 ( docker-py) is in our deps, which is a response to the previous issue with pypiwin32 222

**Comment by xoviat** [comment]
I supposed the pinning can be removed then?

**Comment by pfmoore** [comment]
@tardyp To clarify, the issue is that pip cannot uninstall the current version of pywin32 (whether it's the pypiwin32 build or the pywin32 one), because one of our vendored libraries imports it (and hence locks the DLLs, which is what is causing the permission error on deletion).

There's a fix in pip master, but it can't be released at the moment as we have incomplete changes holding up a release.

Currently, your options are:

1. Use the unreleased pip from git.
2. Avoid needing to uninstall the currently installed version of pywin32 (I guess that's the "unpinning" option).
3. Manually (or via a script that doesn't invoke pip) remove the current pywin32.

It's frustrating to all of us that we can't get a release of pip out with this (and other) fixes, but manpower on pip is severely limited and getting the outstanding work completed is proving to be a challenge.
