### ISSUE TITLE
Encounter com_error when use win32com.client.Dispatch ('word.application')

### ISSUE THREAD

**Issue by Cathay2017** [mhammond/pywin32#1192]
I encounter com_error when I use win32com.client.Dispatch ('word.application')
my PC and software environment are: 
Windows 10, 64bit ;Python = 2.7.14, 64bit;  pywin32-223,64bit; 
Office: WPS Office(10.1.0.6929) from Kingsoft Corp.

Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import win32com
>>> from win32com.client import Dispatch
>>> word = win32com.client.Dispatch ('word.application')

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    word = win32com.client.Dispatch ('word.application')
  File "C:\Python27\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 114, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Python27\lib\site-packages\win32com\client\dynamic.py", line 91, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
com_error: (-2146959355, '\xb7\xfe\xce\xf1\xc6\xf7\xd4\xcb\xd0\xd0\xca\xa7\xb0\xdc', None, None)
>>> 
Please let me know how to sovle this error. Thank you so much in advance!

**Comment by mhammond** [comment]
Please see https://github.com/mhammond/pywin32/blob/master/README.md#support for how to obtain support.

**Comment by muriithiderro** [comment]
Install python for 32 bit, it will solve that issue.

**Comment by AshuR1211** [comment]
Please do not run script AS ADMIN. I was facing same issue with batch file . I run it as normal way
"C:\Python\Python38\python.exe" "A:\Python\mAiLpArSiNg.py"
pause

**Comment by tolunayyy** [comment]
> Please do not run script AS ADMIN. I was facing same issue with batch file . I run it as normal way "C:\Python\Python38\python.exe" "A:\Python\mAiLpArSiNg.py" pause

I was trying to run a script with batch file but my application was IBM's as400 which has an automation library for external programming languages. I was trying to set up a task on the task scheduler on the remote desktop which I am not an admin of. Even though I can run the batch file on the desktop without any errors when I try to run it via Task Scheduler, I get ""pywintypes.com_error: (-2147024703, 'OLE error 0x800700c1', None, None)" error. "  Also,  whenever I try to run that batch file from any location other than the desktop I get the same error. But if I run the file as admin in any other folder, it works. Tricky part is I shouldn't be able to run it as admin because I am not the admin but somehow it works. When I try to make the task scheduler to run it as admin(selecting run with highest privileges) it throws the same error. So the only way to make the batch file run the Python script is either to move it to the desktop and run it manually or move it to another folder and run it as admin. But I need task scheduler to trigger it. I have no idea what is the reason behind it but we tried to log in as admin with the IT guy and it did not work then either.
