### ISSUE TITLE
Deprecation warning about imp module

### ISSUE THREAD

**Issue by melund** [mhammond/pywin32#1256]
When using projects that rely on pywin32 I get a deprecation warning: 
```
pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
```

I am using pywin32 from the conda-forge conda channel. 
``` 
$ conda list pywin32
# packages in environment at C:\Users\mel\anaconda3:
#
# Name                    Version                   Build  Channel
pywin32                   224             py36hfa6e2cd_1000    conda-forge
```

**Comment by carlodri** [comment]
same happening to me here today, during a `pytest` run, using `pywin32` v221:

```
C:\Miniconda3x64\lib\site-packages\win32\lib\pywintypes.py:2
  C:\Miniconda3x64\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp, sys, os
```

**Comment by carlodri** [comment]
the problem still occurs with `pywin32` v224

**Comment by webknjaz** [comment]
Happening with pytest when filterwarnings is set to error: https://ci.appveyor.com/project/CherryPy/cherrypy/builds/27163909/job/0r572kw6vx6g88a6?fullLog=true#L512

@mhammond ^

**Comment by JattMones** [comment]
Without rewriting the existing code, we'd have to find importLibs equivalents to imps "C_EXTENSION, load_module, load_dynamic, and get_suffixes" functions and keywords. Most of these are found in the loop that deals with handling non-windows systems (all except for the load_module). So if you are always running on windows, comment this section out, and replace the with the alternative for load_dynamic.

I believe that these might work (not tested):
imp.load_module = importlib.import_module
imp.load_dynamic = importlib.invalidate_caches(),  importlib.import_module
imp.get_suffix = importlib.machinery.SOURCE_SUFFIXES (I'm pretty sure this one needs to be modified or is incorrect)

imp.C_EXTENSION = 3 (This may need to be modified depending on how we replace get_suffix.)

I'm getting the warning mentioned above when importing win10toast which uses pywin32. However, this file must not be crucial to win10toast, because I can simply remove imp from the import statements, the warning is removed, and everything still runs fine (in otherwords, pywintypes.py is never called). Until the win32 developers find alternatives for the current imp functions and keywords, this may be a temporary fix for you too.

**Comment by brgirgis** [comment]
What is the ETA on this issue to be resolved?

**Comment by henrycjc** [comment]
@brgirgis https://github.com/mhammond/pywin32/issues/1256 this just needs to be released.
