### ISSUE TITLE
CI builds failing with "Cannot open include file: 'EDKMDB.H'"

### ISSUE THREAD

**Issue by mhammond** [mhammond/pywin32#1277]
eg, https://ci.appveyor.com/project/mhammond/pywin32 - but the only failing build is PYTHON_MAJOR=2, PYTHON_MINOR=7; Platform: x64. A quick scan looks like the other builds aren't even trying to build exchance, so I'm a bit confused.

@nczeczulin, so you happen to have any idea what's going on there?

**Comment by nczeczulin** [comment]
I failed to test the build without the exchange sdk installed. But I'm not sure why it is only attempting and failing for 2.7 64bit. It should be attempting and failing for all python 3 64-bit builds.

Since we don't link against an sdk lib, is there an easy way to test for the `edkmdb.h` similar to using `optional_headers`

**Comment by thopiekar** [comment]
Noticed that, too, and contacted the Appveyor people on this.
For me it also makes no sense since 32bit is working.

**Comment by nczeczulin** [comment]
I failed to verify everything still builds correctly if the exchange sdk isn't installed.

`_why_cant_build_extension()` handles the 32-bit case when the required Ex2KSdk library is missing. However, 64-bit builds do not use that library, so it fails when a header is missing instead of skipping the module. I have no idea why Python2/3 behavior differs in the CI builds; both should fail in the same way for 64-bit builds if the sdk is missing.

**Comment by Avasam** [comment]
Is this still relevant with current GitHub actions CI-based builds ?
