### ISSUE TITLE
exeName quotation mark for script win32serviceutil.py

### ISSUE THREAD

**Issue by achillis2016** [mhammond/pywin32#1316]
File : /win32/Lib/win32serviceutil.py
Code in  function InstallService and ChangeServiceConfig:

exeName = '"%s"' % LocatePythonServiceExe(exeName) # None here means use default PythonService.exe

Is the inner quotation mark necessary?

**Comment by thopiekar** [comment]
Yes. If you have a path to an executable with whitespaces, windows will interpret the command including options.

For example:
C:\My program\comserver.exe --run-server

Needs to be:
"C:\My program\comserver.exe" --run-server

Otherwise windows will think
C:\My
Is an executable, with the options
program\comserver.exe --run-server

You kind get the same with bash, if you miss the quotes. The outer quotes are python syntax. 😉

**Comment by achillis2016** [comment]
Thanks for thopiekar.
It's necessary if there is whitespace in executable path , but a little ugly  if there is no whitespace.
So, may be we can add a check  for exeName ?

exeName = '"%s"' % LocatePythonServiceExe(exeName) 
if  ' ' not  in exeName:
    exeName = exeName.strip('"')

**Comment by mhammond** [comment]
> a little ugly

If that's the only reason then I don't think we need to do that.

**Comment by thopiekar** [comment]
@mhammond Got curious and checked it here on Windows with Autodesk Inventor.
Before I was pretty sure what I was saying is correct, but found this:
![image](https://user-images.githubusercontent.com/1847437/53903688-9d265680-4044-11e9-8866-d48e7f19e545.png)

Starting the service works, but why? I mean there is a whitespace between Inventor and 2020 🤔 
Could @achillis2016 be right?

**Comment by mhammond** [comment]
huh - I'm surprised that works. We always use a quote, but I can't see evidence of the way we do things not working.

**Comment by thopiekar** [comment]
Also true 👍
