### ISSUE TITLE
.whl files larger than expected

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#1380]
If you download from here:

https://pypi.org/simple/pywin32

you can check the size:

~~~
$ wc -c pywin32-224-cp36-cp36m-win_amd64.whl
9056372 pywin32-224-cp36-cp36m-win_amd64.whl
~~~

Then if you download Python itself from here:

https://python.org/downloads/release/python-374

you can check the size:

~~~
$ wc -c python-3.7.4-embed-amd64.zip
7504391 python-3.7.4-embed-amd64.zip
~~~

So pywin32 is larger than Python itself. Is this expected?

**Comment by thopiekar** [comment]
If I don't remember incorrectly, the PyWin32 package comes with documentation, too. I think there was a .chm file (html documentation) inside, too.
And yes, I think the size is fine and you probably compare it with the bare minimum of Python - the interpreter and standard modules - so the difference is logical.

**Comment by mhammond** [comment]
I had a quick look and the .whl files seems to have the same as the executables - I suspect the .whl files simply aren't compressed (but I failed to find out how to do that in the minute I spent on it :)

**Comment by Avasam** [comment]
Wheels are already zip files (which works on a per-file compression).
Upstream issues and discussions for potential improvements:
- https://github.com/pypa/wheel/issues/355
- https://github.com/pypa/wheel/issues/247

The currently used `bdist_wheel` command is deprecated, and using any current or future compression improvements from the `wheel` package will require tackling #2208 first

**Comment by Avasam** [comment]
To @thopiekar 's point:
Uncompressed the .chm file is 2.5MB, more than 12% the Windows x86-64 uncompressed wheel
Compressed it accounts for ~1.5MB, almost 19% of the Windows x86-64 compressed wheel
Granted PRs like #2217 and #2218 may change that result a bit in the future.

We could ship a link file to the online doc instead.
Otherwise the wheel size file looks fine, and most improvements are gonna come from upstream.

There's only 80KB of actual html files in win32com.
The rest is actual code.

**Comment by Avasam** [comment]
I'll close this as unactionable.
Note that help files (`.chm`) aren't shipped as of `307`. But that's mostly due to the doc not being built on the CI *yet* since mhammond no longer does local builds. Even if they come back, this stays unactionable (but this issue can be kept in mind for that decision).

To further reduce wheel size, please look at the linked pypa issues above
