### ISSUE TITLE
MinGW handling in setup.py

### ISSUE THREAD

**Issue by joankaradimov** [mhammond/pywin32#1387]
In `setup.py` there are few occurances of `["/SUBSYSTEM:CONSOLE"]`and `["/SUBSYSTEM:WINDOWS"]`. I'd like to replace those with `["-mconsole", "-municode"]` and `["-mwindows", "-municode"]` on mingw. However, I have no access to the `compiler` filed of `build_ext` where those are used.

Any recommendation on how to approach this? Maybe I can introduce an extra argument to `WinExt_win32` and `WinExt_pythonwin`. Or is there some other way to do this?

**Comment by mhammond** [comment]
Sadly overriding this tends to suck a lot, which is why there are subclasses for various distutils/setuptools things in setup.py. You might need to do the same thing (override the compiler classes and arrange for your new classes to be used instead). It's been quite a few years since I had to play with that kind of thing though.

**Comment by joankaradimov** [comment]
This is fixed. I'm closing the issue.
