### ISSUE TITLE
pywin32 for ARM 64 support

### ISSUE THREAD

**Issue by SofianJabal** [mhammond/pywin32#1462]
Hi,

Can you add support to ARM64 architecture?

I tried to compile it but it failed for me with the below message:
LINK : fatal error LNK1355: invalid base address 0x1E7A0000; ARM64 image cannot have base address below 4GB

Thanks,
Sofian.

**Comment by mhammond** [comment]
I'm unlikely to find time to do this myself, but I'm happy to help you. The base addresses are in setup.py.

**Comment by SofianJabal** [comment]
Thanks for the reply, I tried to compile it on amd64 but it still fails

It fails with two errors:
First: 


error: Microsoft Visual C++ 14.1 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

**Comment by SofianJabal** [comment]
I see VS 2019 has SDK version 10, could you please add support to it (you have support only to 8.1)?

**Comment by ader1990** [comment]
Hello @mhammond ,

I have tried to build pywin32 and got to this error:
 error: --plat-name must be one of ('win32', 'win-amd64')

Note that I could successfully build other Python packages on Windows ARM64 like netifaces, comtypes or pymi (my Windows 10 SDK env + VC compiler setup work well).

Any help would be greatly appreciated.

**Comment by ader1990** [comment]
@SofianJabal Did you have any progress on compiling it on ARM64?

**Comment by ader1990** [comment]
Hello,

I have managed to get pywin32 working on windows arm64 (was needed for cloudbase-init):
https://github.com/cloudbase/cloudbase-init-arm-scripts/blob/main/install-cloudbase-init-on-arm64.bat#L45

@mhammond can you please take a look on what I had to change in order to make it compile, so that I can work to have a good patch set to add support for arm version?
https://github.com/ader1990/pywin32/commits/win_arm64

https://github.com/ader1990/pywin32/commit/e7864cdeb9474eb7d5e672ea5aee989f9457362d
https://github.com/ader1990/pywin32/commit/f6795ff6cb91c0c613c23e5bb3897f2e7d45b9f5

This commit removes pythonwin extensions (were not needed for cloudbaseinit, I need to figure out why those extensions do not build):
https://github.com/ader1990/pywin32/commit/8d02293df764e69fdafd225316922a9a806e25b7
Any suggestions are welcome and much appreciated.

Thank you,
Adrian Vladu

**Comment by mhammond** [comment]
Those changes seem trivial and fine. The setup.py change looks odd, but it should be easy to dynamically avoid those extensions if you can detect the platform as setup.py runs.

**Comment by ader1990** [comment]
@mhammond I have made a PR for the ARM64 ifdefs required to build: https://github.com/mhammond/pywin32/pull/161

Thank you,
Adrian

**Comment by Avasam** [comment]
AFAICT, this can be closed as there's ARM64 builds and ARM64 wheels are provided.
Please let us know if you have any other specific issue with ARM64 builds.
