### ISSUE TITLE
PyTime is missing many attributes (like tzinfo) on Python 2

### ISSUE THREAD

**Issue by ofek** [mhammond/pywin32#1546]
* Steps to reproduce the problem.

This demo fails https://github.com/mhammond/pywin32/blob/master/win32/Demos/EvtFormatMessage.py

You can also add:

```python
        time_value, time_variant = result[win32evtlog.EvtSystemTimeCreated]
        if time_variant != win32evtlog.EvtVarTypeNull:
            print(dir(time_value))
```

* Version of Python and pywin32

Python 2.7
v228

**Comment by mhammond** [comment]
By default, because pywin32 predates `datetime`, on Python 2 it uses its own, old, custom object. Years ago I decided that because py3 was a big transition where backward compatibility issues were expected, the default there uses datetime objects.

Further, 228 will be the last pywin32 supporting Python 2, so this is never going to be fixed.

**Comment by ofek** [comment]
Got it, thanks!
