### ISSUE TITLE
Support python 3.10

### ISSUE THREAD

**Issue by KotlinIsland** [mhammond/pywin32#1588]
`pip install pywin32`
```
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
```

**Comment by mhammond** [comment]
It turns out this is tricky due to the removal of the old buffer API. In particular, it appears as though the many uses of `PyWinObject_AsReadBuffer` don't have a trivial change to get things working. I'd love some help here.

**Comment by RoccoMatano** [comment]
Since I am interested in pywin32 supporting python 3.10 and I have a little experience in python C extensions, I would like to help.

I think that those spots where `PyObject_AsReadBuffer` or `PyObject_AsWriteBuffer` are used locally can easily be replaced by a pair of `PyObject_GetBuffer` and `PyBuffer_Release`, which is the way to handle buffer access according to the new buffer protocol. But unfortunately there are those functions `PyWinObject_AsReadBuffer` and `PyWinObject_AsWriteBuffer`. They are used quite often (approx. 80 times) and hand out the buffer address and length to external clients, so that they cannot know, when to release those buffers by calling `PyBuffer_Release`.

Am I right in believing that changing/replacing `PyWinObject_AsReadBuffer` and `PyWinObject_AsWriteBuffer` would require a major refactoring? If so, I think I cannot be of any help, since I never worked on pywin32 before.

**Comment by RoccoMatano** [comment]
@mhammond Do you think it would be a viable solution to replace `PyWinObject_AsXBuffer` with a pair of `PyWinObject_AquireXBuffer` and `PyWinObject_ReleaseBuffer` respectively, so that the callers of `PyWinObject_AsXBuffer` would have to worry about releasing the buffers in the future?

**Comment by mhammond** [comment]
> Do you think it would be a viable solution to replace `PyWinObject_AsXBuffer` with a pair of `PyWinObject_AquireXBuffer` and `PyWinObject_ReleaseBuffer` respectively

That sounds reasonable (although a C++ RAII class might be even better and easier for callers)



> so that the callers of `PyWinObject_AsXBuffer` would have to worry about releasing the buffers in the future?

You mean *not* worry there, right?

> If so, I could try that.

That would be awesome!

**Comment by kxrob** [comment]
The problem or non-problem is that it would be a lot of work to figure out in each affected location in pywin32, when and how to do the `PyBuffer_Release()` fully according to the book. And on the other side the classic buffer interface in Py 3.9- internally just used the new `PyObject_GetBuffer()` and called ..Release() immediately in a "cheap" way. 
There are no essential changes, just the cheap interface was removed.

In those (simple) use cases in pywin32 (and probably in most practical cases) it is clear from the application logic that the object 
exposing the buffer lives long enough and in a (constant) manner not changing its buffer location. The release() signalling interface is designed for rather advanced cases ...

Thus I already made a rather simple patch to get it compile (almost): when version > Py3.10, it puts a replacement for the cheap buffer interface.  There were a few other things to be tweaked to get it compile with Py3.10.  So far it compiles most modules, and I made few tests by hand to import them - which seems ok.
When I put it aside last, the build stopper was, that Py3.10 uses version strings in the filenames of .pyd's. This breaks file copies, verstamps and maybe more in setup.py. And it seems, this also confuses and breaks the win32ui import or Pythonwin start (error due to that self-locating / glue issue which was a problem recently). Hope it is one of the last problems. 

I could put a draft PR sooner or later if this is interesting so far.

**Comment by mhammond** [comment]
> In those (simple) use cases in pywin32 (and probably in most practical cases) it is clear from the application logic that the object
> exposing the buffer lives long enough and in a (constant) manner not changing its buffer location. The release() signalling interface is designed for rather advanced cases ...

I guess my main concern there is that some users might end up passing objects with these "advanced use cases" to pywin32. It's the nature of the buffer interfaces that we can only inspect the pywin32 side of the interaction.

(That said though, I guess I'd rather have that than nothing :)

>  the build stopper was, that Py3.10 uses version strings in the filenames of .pyd's.

Ouch - I didn't realize those names were mandatory now. I'm getting quite unhappy with the state of the python world in terms of backwards compatibility - killing bdist_wininst was a bit of a final straw for me :(

**Comment by RoccoMatano** [comment]
>You mean not worry there, right?

No, that was not what I meant. My idea was to put the burden of releasing the buffers on the callers, since only they can know how long they need the buffer.
Sure, RAII could make such a switch easier.

I aleady thougt about @kxrob's  idea of 'copying' py3.9s way of implementing `PyObject_AsReadBuffer` or `PyObject_AsWriteBuffer` (hoping the lifetime of the underlying object will be sufficient) , but since that went against my gut feeling, I thougt, I shouldn't propose it.

Now I lerarned that a) there is a competing proposal (that is further along than my suggestion) and b) that solving the buffer problem is not sufficient to build with py3.10. That leaves me unsure whether it would still make sense for me to go through the trouble of creating a PR that just resolves the buffer problem in a different way.

**Comment by mhammond** [comment]
> since that went against my gut feeling, I thougt, I shouldn't propose it.

Yeah, that was my reaction, and I was under the assumption that it changed for some concrete reason, so the "simple" strategy might not work in the longer term. I doubt @kxrob would be upset if your proposal was implemented :)

> that solving the buffer problem is not sufficient to build with py3.10.

No, but it's a required step on the path.

**Comment by RoccoMatano** [comment]
@mhammond One more question, before I start to prepare a PR: Replacing the usage of `PyWinObject_AsXBuffer` with a RAII based class would also require to replace the corresponding exports of the `pywintypes` DLL by exporting that future class. Is that OK for you? I guess so, since `pywintypes` exports are already C++ mangled names.

**Comment by mhammond** [comment]
Yep, that's fine!

**Comment by RoccoMatano** [comment]
@mhammond I hit a road bock :disappointed: :
win32gui.i has four typemaps for MENUITEMINFO and MENUINFO dealing with buffers. By default SWIG puts those code snippets from typemaps into their own code blocks { ... }. That is inappropriate for placing a RAII object there,  since that would make the dtor of that object being called too early. In any SWIG version that is newer than that ancient one that pywin32 is using, this problem could easily be mitigated by using the `noblock=1` attribute for the typemap, but for SWIG version 1.1 that attribute results in a syntax error. Unfortunately that SWIG in pywin32 seems to be a patched version, so that it cannot easily replaced. At the moment I am clueless, how to proceed. Do you have any advice?

**Comment by mhammond** [comment]
Ouch. I don't see any obvious answers here, and I probably will not have time to dig deeper for at least a week.

**Comment by RoccoMatano** [comment]
After sleeping on it once, I now have an idea how to get around the typemap problem: Write the wrapper code by hand instead of leaving it to SWIG.

@kxrob Slowly I am getting the idea that your approach might be the better one after all. :thinking:

**Comment by pewscorner** [comment]
The python [3.10.0rc1 changelog](https://docs.python.org/3.10/whatsnew/changelog.html#python-3-10-0-release-candidate-1) mentions `bpo-41103: Reverts removal of the old buffer protocol because they are part of stable ABI`. Does this mean that there is no longer anything preventing pywin32 from working on python 3.10?

**Comment by kxrob** [comment]
> `bpo-41103: Reverts removal of the old buffer protocol because they are part of stable ABI`. Does this mean that there is no longer anything preventing pywin32 from working on python 3.10?

The old buffer protocol is anyway not used anymore since 9562f8c. 
I've put other changes required for Py3.10 in PR #1664, and just rebased it onto current master and cleaned it up somewhat. See comments over there. It (still) works so far regarding the CI test runs - which also do provide Py3.10 binary wheels for further testing ...  (Test feedback is appreciated before considering a merge.)

**Comment by clin1234** [comment]
Is there a work in progress in pushing wheels for 3.10?

**Comment by mhammond** [comment]
CI does build wheels - the latest can be found at https://github.com/mhammond/pywin32/actions/runs/1250371344

**Comment by ideepthinv** [comment]
I am still facing this issue.

  RuntimeError

  Unable to find installation candidates for pywin32 (306)

  at /usr/local/lib/python3.10/site-packages/poetry/installation/chooser.py:73 in choose_for
       69│ 
       70│             links.append(link)
       71│ 
       72│         if not links:
    →  73│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       74│ 
       75│         # Get the best link
       76│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       77│ 

Cannot install pywin32.
