### ISSUE TITLE
Bug: win32ui and Pythonwin.exe on 64 bit Windows

### ISSUE THREAD

**Issue by OlegLxx** [mhammond/pywin32#1598]
Hello! I found a bug in the compiled build pywin32-228.win-amd64-py3.9.exe

Expected behavior: 
When you open the Pythonwin.exe application, there should be an IDE window. 
If you use import win32ui in your code, it shouldn't cause an error.

Actual behavior:
When opening the Pythonwin.exe application, an error appears: 'still can't get my hands on win32ui'
If you use import win32ui in your code then the error appears: 'ImportError: DLL load failed while importing win32ui: A dynamic link library (DLL) initialization routine failed.'

Steps to reproduce the problem:
1. Install the 64-bit version of Python 3.9 (python-3.9.0-amd64.exe)
2. Install the 64-bit version of pywin32 228 (pywin32-228.win-amd64-py3.9.exe)
3. Open ..\Python39\Lib\site-packages\pythonwin folder and run Pythonwin.exe application.
4. Run Python IDLE and write: import win32ui

Operating System: Windows 10 Enterprise LTSC 64-bit (10.0, Build 17763)
Version of Python: 3.9.0 x64
Version of pywin32: 228-cp39-x64

p.s.
If I install pywin32 via pip as a * .whl package from https://www.lfd.uci.edu/~gohlke/pythonlibs/ then the error does not appear.
![pywinbug](https://user-images.githubusercontent.com/73443706/97118325-80a7c800-171a-11eb-871e-78aad356cbdd.jpg)

**Comment by kxrob** [comment]
Consider if the bug was already solved recently - likely by the fix for #1593 some 3 days ago at least.
Indeed your uci.edu wheel link goes to a brand new unofficial build from yesterday.
To verify you can pick a latest / recent wheel right here from the CI build artefacts via the "Actions" tab. Recent https://github.com/mhammond/pywin32/actions/runs/325502510 completed for py3.9 .  
(Randomly the CI job from some versions run incomplete even without test errors - probably because of the runtime approaching critical github resource limits. See on the left side.)

**Comment by OlegLxx** [comment]
Sorry. I close.

**Comment by sschukat** [comment]
On my machine the fix #1593 solves the error if win32ui is imported in Python itself. If PythonWin as a MFC application bootstraps Python in Win32uiHostGlue::DynamicApplicationInit this leads to another error. The CEnterLeavePython instance in CCtrlView_Type::PyCCtrlView_Type tries to acquire the GIL but at this stage during the LoadLibrary of win32ui the interpreter is not initialized which again leads to an access violation
The bootstrap starts with loading of win32ui
```cpp
inline BOOL Win32uiHostGlue::DynamicApplicationInit(const TCHAR *cmd, const TCHAR *additionalPaths)
...
    // try it simple - if we can load the module we are done.
    HMODULE hModWin32ui = LoadLibrary(szWinui_Name);
```
this triggers the static initializer 
```cpp
inline PyCCtrlView_Type::PyCCtrlView_Type(const char *name, ui_type *pBaseType, ui_type_CObject *pControlType,
...
    if (pControlType != this) {
        CEnterLeavePython celp;
```
which uses
```cpp
PyGILState_Ensure(void)
{
    /* Note that we do not auto-init Python here - apart from
       potential races with 2 threads auto-initializing, pep-311
       spells out other issues.  Embedders are expected to have
       called Py_Initialize(). */

    /* Ensure that _PyEval_InitThreads() and _PyGILState_Init() have been
       called by Py_Initialize() */
    if (tcur == NULL) {
        /* Create a new Python thread state for this thread */
        tcur = PyThreadState_New(gilstate->autoInterpreterState);  // <-- GilState is NULL and triggers the access violation
```
which relies on Py_Initialize, which is not called at that time and causes an access violation. The Py_Initialize is called further down in the function. 
```cpp
inline BOOL Win32uiHostGlue::DynamicApplicationInit(const TCHAR *cmd, const TCHAR *additionalPaths)
...
    HMODULE hModWin32ui = LoadLibrary(szWinui_Name);
...
    void(__cdecl * pfnPyInit)(void);
    pfnPyInit = (void(__cdecl *)(void))GetProcAddress(hModCore, "Py_Initialize");
    if (pfnPyInit && bShouldInitPython) {
        (*pfnPyInit)();
``` 
I don't know if how sensitive the startup sequence is or if the settings of the base classes could be moved to an init function, but I'll try both. @mhammond do you have any other ideas?

**Comment by mhammond** [comment]
This is all very messy. On my machine I don't have this exact problem because those "early" `LoadLibrary()` calls fail, causing that code to load and init Python before retrying the load of win32ui.

I'd like to know what's changed in Python to make this no longer work, but regardless, `DynamicApplicationInit()` looks plain wrong in that regard - for better or worse, win32ui is going to call Python as part of initializing, so it's necessary Python be initialized before that happens - and it's clear that doesn't always happen.

The reason those first LoadLibrary calls fail is because we can't load Python itself - the pythonxx.dll isn't on a global PATH for me. So after win32ui fails to load, we go looking for pythonxx.dll - and initialize it - before then trying to load win32ui (which then works).

I *think* the reason `DynamicApplicationInit()` does things that way was to try and avoid second-guessing Windows in terms of locating the python dll - ie, if that first call worked, we don't have to go searching and locate one that's different than Windows would have chosen.

So I think the right thing to do is to simply remove the ["try it simple" block](https://github.com/mhammond/pywin32/blob/49118d66439991f98b405fc3bf5835b37f2f8b06/Pythonwin/Win32uiHostGlue.h#L154-L162), so we always load and init Python first, then import win32ui.

(I'm out of time to look at this for probably a few days at least. However, I did find some other "gil state" and other issues I pushed a fix to, so a 3.9 pythonwin starts correctly when pythonXX.dll isn't on my path. It would be great if you can have a poke)

**Comment by sschukat** [comment]
Hi I looked into the changes between Python 3.8 and Python 3.9. The change in behavior is caused from my point of view through the change in accessing the GCState.  In Python 3.8 the GCState was a member of the static variable PyRuntime defined in pycore_pystate.h 
```c
...
typedef struct pyruntimestate {
...
    struct _gc_runtime_state gc;
}
...
PyAPI_DATA(_PyRuntimeState) _PyRuntime;
```
and accessed in _gcmodule.c directly
```c
_PyObject_GC_Alloc(int use_calloc, size_t basicsize)
{
    struct _gc_runtime_state *state = &_PyRuntime.gc;
...
```
In Python 3.9 the GCState is now a member of the current interpreterstate in the threadstate.
```c
typedef struct _ts PyThreadState;
typedef struct _is PyInterpreterState;

struct _ts {
...
    PyInterpreterState *interp;
...
}
...
struct _is {
...
    struct _gc_runtime_state gc;
}
```
and accessed in _gcmodule.c 
```c
_PyObject_GC_Alloc(int use_calloc, size_t basicsize)
{
    PyThreadState *tstate = _PyThreadState_GET();
    GCState *gcstate = &tstate->interp->gc;
```

Hence you'll get an access violation now if you want to create any Python memory if the interpreter is not initialized. Which is the case if you want to create a tuple in the static constructor of PyCCtrlView_Type. I'll now look into a change of the initialization sequence in `DynamicApplicationInit()` to avoid this problem.

**Comment by mhammond** [comment]
>  I'll now look into a change of the initialization sequence in `DynamicApplicationInit()` to avoid this problem.

Thanks, but I actually did this over the weekend - I hope you didn't spend too much time on this.

**Comment by sschukat** [comment]
> Thanks, but I actually did this over the weekend - I hope you didn't spend too much time on this.

No, I just checked again the different ways how loading of libraries could be influenced.
