### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)

### ISSUE THREAD

**Issue by MohammadAarizMahfooz** [mhammond/pywin32#1609]
I am using pypy3 for my project and it requires pywin32.  
When I am writing `pypy3 -m pip install pywin32` it is showing error  

- I was expecting it should ne installed but this won't happen

- When I am running `pypy3 -m pip install pywin32` command in terminal it is showing this
`ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none) `
`ERROR: No matching distribution found for pywin32`
![Screenshot (47)](https://user-images.githubusercontent.com/72154241/98369918-bb392b00-205f-11eb-9111-e602da6d512f.png)
- Version of Python is 
`Python 3.6.9`
- Version of PyPy is  
`PyPy 7.3.2 with MSC v.1927 32 bit`

**Comment by vernondcole** [comment]
There are many modules in pywin32 which are written in C++ as CPython callable objects. AFAIK, pypy code cannot call them. (If I am wrong, someone please let me know.) So to use pywin32 modules, you will need to be running old-fashioned Python3 -- not pypy.

**Comment by magikmw** [comment]
I'm running into the same problem with plain python `3.8.5` and pip `20.0.2`.

**Comment by vernondcole** [comment]
Correct.
When you are running inside WSL2, you are running on Linux. That's the "L" in WSL. If you want to call Windows COM objects, you need to be running inside the Windows part of things. The Linux subsystem does not support COM. All of the Windows magic that pywin32 makes possible comes from various COM calls. No COM, no magic.

So it would be more precise to say "WSL does not support pywin32" rather than "pywin32 does not support WSL".

**Comment by MainRead** [comment]
Amin
