### ISSUE TITLE
Command line arguments to PythonWin are ignored

### ISSUE THREAD

**Issue by dougransom** [mhammond/pywin32#1620]
Note that issues in this repository are only for bugs or feature requests in the pywin32.
 
The command line arguments to pythonwin don't seem to work anymore.

PS C:\Python38-32\lib\site-packages\pythonwin\pywin\Demos> ..\..\pythonwin /run createwin.py
PS C:\Python38-32\lib\site-packages\pythonwin\pywin\Demos> ..\..\pythonwin /edit createwin.py
PS C:\Python38-32\lib\site-packages\pythonwin\pywin\Demos> ..\..\pythonwin /app createwin.py

The above i would thing should edit or run the applications.

 * Version of Python and pywin32
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:37:30) [MSC v.1927 32 bit (Intel)] on win32
pywin32 300  (as show by pip).

**Comment by kxrob** [comment]
I think that never did work so far on Python 3.8+ before. It was recently fixed for Python3.7 , which got into b300.  But Py3.8 had again changed initial sys.path setup, which confused win32ui. Which Py & Pywin32 version was working?

PR #1622 now hopefully enables that. You can download pre-compiled wheels as CI test runner "Artifacts" of that PR ( [here](https://github.com/mhammond/pywin32/pull/1622/checks?check_run_id=1455178614) - except Python3.9win32 which timed out - or more upon further push / merge)  - as soon as the CI stops with final timeout.

Further notes:
* Best don't use the slash options like  `/edit`,  `/run` ... anymore - which cause sys.path[0] to become `C:\` or so due to Python behavior - but rather the new `-edit` , `-run`, `-new`, `-goto:LINE` (after each file arg) ...
* Edit can also be started without -edit by   `....\pythonwin ...\createwin.py` . The difference is that sys.path[0] becomes the script directory even when CWD is different.
* I added new Explorer Python script context commands to directly `Run in Pythonwin` and `Edit in new Pythonwin` - when `\PythonXX\Scripts\pywin32_postinstall.py` is run (as admin) after wheel installation, which also registers COM servers, help files etc.
*  `/app` doesn't make sense with that kind of non-app script 
* There is a new and updated ../Pythonwin/start_pythonwin.pyw which can alternatively startup the Pythonwin IDE with a normal python(w).exe - it existed in the sources, but was not distributed so far and needed fixes regarding 3d dialog controls which are drawn by PY3 python.exe manifests.

* I noticed further on one machine, that when CWD is not in the python.exe directory the Pythonwin.exe doesn't start in case a machine has no vcruntime140.dll pre-installed in system32 - as it doesn't find the one besides python.exe . A manual copy / link helps in that case. Another issue -> #1624 . Though that seems not to be the case in your installation.

**Comment by mhammond** [comment]
This should be fixed in the most recent build!
