### ISSUE TITLE
Help  not working in PythonWin

### ISSUE THREAD

**Issue by dougransom** [mhammond/pywin32#1621]
* Steps to reproduce the problem.

use the menus help/pythonwin reference.

* Version of Python and pywin32
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:37:30) [MSC v.1927 32 bit (Intel)] on win32
pywin32 build 300

**Comment by metolone** [comment]
Same issue, but it isn't help/pythonwin reference that fails, it is "Help/Python Manuals".  specifically, I tracked it down with Process Monitor to the registry key "HKEY_CURRENT_USER\SOFTWARE\Python\PythonCore\3.8\Help\Main Python Documentation" pointing to python381.chm instead of python386.chm.  Patch that registry key as a workaround.

**Comment by metolone** [comment]
FYI, there's also a "HKEY_CURRENT_USER\SOFTWARE\Python\PythonCore\3.8\Help\Pythonwin Reference" key but that one had a correct path.

**Comment by kxrob** [comment]
Did you install via pip wheel,  or full installer - with or without system install? The Python installation was with CHM?
After a pip install the `...\PythonXX\Scripts\pywin32_postinstall.py -install` needs to be run (as admin) which tries to register the help files. 
The pip wheels so far also seem not to contain a PyWin32.chm  - would require an extra download and placement in site-packages.

**Comment by metolone** [comment]
I installed from full installer for Python and PyWin32.  CHM was included.  There is a PyWin32.chm dated 11/14/2020.  The changelog only lists up to v228 but I installed v300.

**Comment by kxrob** [comment]
@dougransom  "on win32 pywin32 build 300" : There was indeed a bug (in pywin32_postinstall.py) concerning all 32bit installations on Win64 since long / ever.  Fix added to PR #1622 - see CI test build artefacts for wheels.

@metolone "`HKEY_CURRENT_USER\SOFTWARE\Python\PythonCore\3.8\Help\Main Python Documentation`" :
This key is made from a 64bit installer of core Python - and is seen by 64bit PythonWin independent of setup needs/clues.  In case of false content in that key the Python installer would to be blamed - not pywin32. However in the Python installer one can click away the documentation CHM install / update ... and its unclear if both 32bit + 64bit installations are around in your case ...

The help links for 32bit on Win64 have to be in a locations like this:
`HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Python\PythonCore\3.8-32\Help\Pythonwin Reference`

The wheels (which are zip archives) don't contain a PyWin32.chm so far. Possibly intended.? But the postinstall script does register the location a pre-existing one (from a full installer or manual copy).
