### ISSUE TITLE
ArcGis 10.8 and Python 2.7 

### ISSUE THREAD

**Issue by ernestooa** [mhammond/pywin32#1721]
Sorry about my ignorance, but, if I have ArcGis 10.8 and it comes with Python 2.7, that means that I can not use Python 3.x and therefore I can not use pywin32 3.x and therefore I can not use MGET?

**Comment by vernondcole** [comment]
Some discussion seems to be in order. . . .

ArcGis 10.8 comes with a packaged version of Python 2.7, it is true. 

I have been given to believe that it is an Anaconda version of Python, if so it may already include pywin32. (I do not have ArcGis, so cannot test this.)
Otherwise, look online for instructions for installing  Python modules in the ArcGis embedded Python, and do "conda install pywin32==228" or "pip install pywin32==228" whichever works for you.  Note that version 228 is the latest which  will ever work for Python 2.7. Python 2.7 is no longer supported officially, but ESRI says that they will support their embedded version.

If you do not need to interact with ArcGis, you can always install Python3 from the http://python.org site or elsewhere. Multiple installations of Python will not interfere with each other. You start python.org versions by typing only "py" (rather than "python") on Windows.

Finally, the only MGET thing I know about is a function of ftp, which has nothing to do with pywin32 or Python. My copy of Windows 10 has ftp installed.

Good luck and welcome to the world of Python.
