### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by Kingsleyhsu46671** [mhammond/pywin32#1899]
Is the win32api free for commercial use?
Can I use it in my company to exucute project for no any cost?

**Comment by sschukat** [comment]
The PyWin32 package is licensed under a permissive open source licenses see [com license](https://github.com/mhammond/pywin32/blob/main/com/License.txtl), [win32 license](https://github.com/mhammond/pywin32/blob/main/win32/License.txt) , [pythonwin license](https://github.com/mhammond/pywin32/blob/main/Pythonwin/License.txt), (scintilla)[https://github.com/mhammond/pywin32/blob/main/Pythonwin/Scintilla/License.txt] which allows you to use it in source or binary form for any use as long as you reproduce the license and copyright text with your software. 

If you are distributing also the adoapi, the [license](https://github.com/mhammond/pywin32/blob/main/adodbapi/license.txt) is a weak copyleft license [LGPL](https://tldrlegal.com/license/gnu-lesser-general-public-license-v2.1-(lgpl-2.1)) which has some restrictions but none for commercial use. 

Hence, yes you can use it without any license cost, but you must oblige to the license conditions otherwise you'll loose the right to use the software.
