### ISSUE TITLE
deprecate exe installers

### ISSUE THREAD

**Issue by mhammond** [mhammond/pywin32#1939]
As noted in https://github.com/mhammond/pywin32/pull/1936#discussion_r951105482, .exe installers are deprecated almost everywhere else, and deleted from recent setuptools. Our CI no longer creates them to avoid pinning to old versions. The build environments necessary to create .exe installers are therefore stranded.

So we should formally deprecate our installers - something like:

- [x] document it in README, invite discussion here.
- [x] have the installers note it in the next release, pointing here.
- [ ] make whatever changes we can identify to smooth things for such users.
- [ ] stop producing them.

**Comment by Avasam** [comment]
@mhammond Other than "invite discussion here." and "pointing here.", it seems that the first 2 points are complete.

For point 3, is there anything that the installers still do that PyPI wheels don't?

For point 4, https://mhammond.github.io/pywin32_installers.html says:
> you can't make them with recent versions. So at some point in the future they can't be provided.

Which gives a current ETA of when Python 3.9 support is dropped (so some time after September 2025), since pywin32 is currently using Python 3.9 to build 3.10+ installers. Does that sound correct or do you have any plans of dropping them sooner?

**Comment by mhammond** [comment]
I have no plans here at all - these .exe artifacts have been downloaded many thousand times for the latest release, so I'll keep them alive as long as practical, but at some point I'll give up.
