### ISSUE TITLE
Possible win32gui.GetMenu() bug in Windows 11?

### ISSUE THREAD

**Issue by Kalmat** [mhammond/pywin32#2009]
Hi! Thank you so much for your work and for sharing!

Since I updated to Windows 11, win32gui.GetMenu() is returning 0.

I have made this simple script to test it:

```
import time
import win32gui
import pywinctl as pwc

print("Open notepad and press Ctl-C when you're done")
while True:
    try:
        time.sleep(1)
    except KeyboardInterrupt:
        break
print("Click on notepad and keep it as the active window")
for i in range(5, 0, -1):
    try:
        print("You have %s seconds remaining" % str(i))
        time.sleep(1)
    except KeyboardInterrupt:
        break
win = pwc.getActiveWindow()
hWnd = win.getHandle()
print("Window handle:", hWnd, win32gui.GetWindowText(hWnd))
hMenu = win32gui.GetMenu(hWnd)
print("Menu handle:", hMenu)
```

My setup info:
    pywin32 version: 304
    python version: 3.9.13

EDIT: I upgraded both to:
    pywin32 version: 305
    python version: 3.11.1
... with the same result (menu handle returned is 0)

Thanks in advance!

**Comment by mhammond** [comment]
`win32gui.GetMenu` is a tiny wrapper around the Windows `GetMenu` function - takes a HWND, returns a HMENU. I've no idea why it isn't working in your use-case in Windows 11 - probably because how Notepad implements menus have changed. https://github.com/mhammond/pywin32#support might help, although you probably need to look wider - this isn't going to be a Python specific change.

**Comment by Kalmat** [comment]
Thank you for your quick reply! I will keep trying to find the reason why it's failing now. Just for clarification, my example uses notepad, which is quite "standard", but it fails with all the apps I have tried so far.

Thanks again for your work!
