### ISSUE TITLE
`pip install pywin32` Could not find a version that satisfies the requirement pywin32

### ISSUE THREAD

**Issue by lipeeeee** [mhammond/pywin32#2066]
I have seen many inconsistent anwsers in this issue, when installing pywin32 via pip like this: `pip install pywin32 --verbose`, i get this:
```
Using pip 22.0.2 from /home/lipe/.cache/pypoetry/virtualenvs/test-upMdWshG-py3.9/lib/python3.10/site-packages/pip (python 3.10)
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
```

I have tried with multiple python, pip and pywin32 versions, all failed, currently im using:
* python 3.10
* latest pywin
* pip 22.0.2

I'm in a linux environment(wsl)

**Comment by vernondcole** [comment]
The answers are not inconsistent in this case.
Since the purpose of pywin32 (did you notice the "win"?) is to provide hooks to Windows system functions, it is not intended to work on anything other than Windows.
You are running under Windows Subsystem for Linux, which is an excellent test environment, but it has no access to Windows COM services -- it is a version of Linux.
If you want to use Windows services, such as those provided by pywin32, you will need to step back to your native Windows environment.
