### ISSUE TITLE
Cannot install pywin32 using poetry on Jenkins. What is an alternate lib I can use?

### ISSUE THREAD

**Issue by ideepthinv** [mhammond/pywin32#2192]
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

* Steps to reproduce the problem.

* Version of Python and pywin32

**Comment by mhammond** [comment]
pywin32 is for access to the windows API - you probably don't need an alternative for jenkins if you aren't running it on windows.

**Comment by Avasam** [comment]
@ideepthinv It would be useful if you gave information about your Jenkins environment (unix vs windows, etc.), the version of python, pywin32 and poetry you're using, and most importantly, the error you're seeing.

Otherwise, there's not much that can be done other than assuming you're trying to install on a jenkins Unix environment.
