### ISSUE TITLE
StarTeam object causes interpreter bug

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#51]
i try to use python to access the StarTeam COM 
interface thru automation \(StarTeam is a source-control 
system: http://www.borland.com/starteam/\). i do the 
following:

import win32com.client
from win32com.client import Dispatch
f = Dispatch\('StarTeam.StServerFactory'\)
s = f.Create\('&amp;lt;server&amp;gt;', &amp;lt;port&amp;gt;\)

at this point, the interpreter seems to break. anything i 
write \(and i mean \*anything\*\) results in

File &amp;quot;&amp;lt;stdin&amp;gt;&amp;quot;, line 1
dir\(\)
^
SyntaxError: invalid syntax

this behavior has been observed both in Python 2.3 with 
the appropriate win32all extensions and in ActivePython 
2.2.

Reported by: clechasseur_c

Original Ticket: "pywin32/bugs/51":https://sourceforge.net/p/pywin32/bugs/51

**Comment by Avasam** [comment]
Caused by user not replacing the angle brackets in placeholder values

**Comment by Avasam** [comment]
(sorry accidentally closed). This is gonna be hard to test as StarTeam, and its owner company, has changed hands a couple hands and is currently a paid product with no trial.

**Comment by Avasam** [comment]
I've managed to contact and confirm the original poster for this issues (thanks for answering back)

> [...]
> As you can probably guess, it's been years since I've used StarTeam (I didn't even know the product still existed TBH). So I suppose you can just close the bug as "being 21 years old". :)

\- @clechasseur

Since this is specific to an application that we can't test or replicate. That the issue may have been caused by a specific version of the application at the time. And that OP has confirmed this is no longer relevant to him. I'll close this issue.
