### ISSUE TITLE
problems installing pywin32-216.win32-py3.1.exe

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#556]
Hi, regarding issue 3290176, same problem occurs with installation file pywin32-216.win32-py3.1.exe.
Is it possible to generate a new installation file with the fixed postinstall script?
Thanks\!\!

Reported by: antoniobotelho

Original Ticket: [pywin32/bugs/556](https://sourceforge.net/p/pywin32/bugs/556)

**Comment by Avasam** [comment]
Since 71afa71e11e6631be611ca5cb57cda526b5e91ab, the `PATH` is now prepended, rather than appended. For Python >= 3.8, the `PATH` environment variable isn't even used. This is included in pywin32==226.

Python 3.7 has also reached EOL (meaning no security fixes/support) and I'd recommend migrating over to 3.8+ (see #2207)

[.exe installers are now deprecated](https://github.com/mhammond/pywin32#binaries) #1939, so you should install from PyPI (ie: `pip install pywin32>=226`)

Given the sheer amount of installation issue duplication and old history, I'd like to consolidate the current state of these issues. So I'll close and reference back any issue that only has comments showing the issue:
- from before November 10th, 2019 (pywin32<226)
- using `.exe` installers
- using Python < 3.8

Please also try https://github.com/mhammond/pywin32#troubleshooting before opening a new issue, or let us, and others, know if it **did** resolve your issue.
