### ISSUE TITLE
some imports changed from relative to absolute in 218

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#620]
some imports in win32comext changed from relative to absolute in pywin32-218.win32-py3.2.exe
attaching diff between pywin32-217.win32-py3.2.exe and pywin32-218.win32-py3.2.exe

win32com.adsi module now don't work:
Python 3.2.3 \(default, Apr 11 2012, 07:15:24\) \[MSC v.1500 32 bit \(Intel\)\] on win
32
Type "help", "copyright", "credits" or "license" for more information.
&gt;&gt;&gt; import win32com.adsi
Traceback \(most recent call last\):
File "&lt;stdin&gt;", line 1, in &lt;module&gt;
File "C:\Python32\lib\site-packages\win32comext\adsi\\\_\_init\_\_.py", line 25, in
&lt;module&gt;
from adsi import \*
ImportError: No module named adsi

Reported by: mjezek

Original Ticket: [pywin32/bugs/620](https://sourceforge.net/p/pywin32/bugs/620)

**Comment by bobince** [comment]
This was mysteriously fixed in the 225 wheels, where win32comext.adsi.__init__.py has “from .adsi import *”.

It was equally-mysteriously broken again in the 226 wheels.

I can't see any relevant code changes in the commit history, so there must be something different about lib2to3 in the external build environment.

I suggest we just change it to “from .adsi import *” in the source code, now we don't have to support Python < 2.5.

**Comment by bobince** [comment]
https://github.com/mhammond/pywin32/pull/1461
