### ISSUE TITLE
DLL load fails when on any drive other than C:

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#753]
If the current working directory is not in the C: drive, then importing the `win32api` module will fail.

~~~
I:\>python
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified path is invalid.
>>> quit()

I:\>C:

C:\>python
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32api
>>> # No traceback is appears.
>>> quit()

C:\>
~~~

As you can see in the example above, when the command prompt is in the I: drive, the import statement fails. If the user switches to the C: drive and tries again, then the import statement succeeds.

Reported by: wecsam

Original Ticket: [pywin32/bugs/753](https://sourceforge.net/p/pywin32/bugs/753)

**Comment by Avasam** [comment]
Since 71afa71e11e6631be611ca5cb57cda526b5e91ab, the `PATH` is now prepended, rather than appended. For Python >= 3.8, the `PATH` environment variable isn't even used. This is included in pywin32==226.

Python 3.7 has also reached EOL (meaning no security fixes/support) and I'd recommend migrating over to 3.8+ (see #2207)

[.exe installers are now deprecated](https://github.com/mhammond/pywin32#binaries) #1939, so you should install from PyPI (ie: `pip install pywin32>=226`)

Given the sheer amount of "ImportError: DLL load failed" issue duplication and old history, I'd like to consolidate the current state of these issues. So I'll close and reference back any issue that only has comments showing the issue:
- from before November 10th, 2019 (pywin32<226)
- using `.exe` installers
- using Python < 3.8

Please also try https://github.com/mhammond/pywin32#troubleshooting before opening a new issue, or let us, and others, know if it **did** resolve your issue.
