### ISSUE TITLE
Need documentation separate from kit

### ISSUE THREAD

**Issue by ghost** [mhammond/pywin32#789]
I've found a number of pointers to this package, but
nothing - not even an FAQ entry - giving a detailed
list of the current contents or installation
requirements/instructions.  

The closest I've found is the page at
http://www.python.org/windows/win32.  But that isn't
very clear or consistent, and just confuses things
more. I'd like to see a list that is a bit more
detailed \(at least to the level of "base services,
common controls, etc." - as listed in the MSDN docs\),
without inconsistencies \(are memory mapped files part
of the API or aren't they\).

I'd also like basic installation instructions:  Which
versions of Python are supported, does the installation
give me a choice of which components to install, what
changes it makes to the registry, how to uninstall,
etc.  The fact that the install is an .exe and not an
.msi or setup.exe opens some questions that need to be
addressed, even if it's just to say that the .exe is a
standard windows installation kit.

Gary

Reported by: garyfx

Original Ticket: "pywin32/feature-requests/30":https://sourceforge.net/p/pywin32/feature-requests/30

**Comment by Avasam** [comment]
Thanks to wheels, and the exe installers being deprecated, installation requirements are now found in the setup file and handled by your package manager of choice (eg: pip)

As for listing the public API, parameters, return types, etc,, https://pypi.org/project/types-pywin32/ is pretty much *the* source of truth. With the eventual goal of bringing back type hints in source (see work like #2102). Although C-extensions are likely gonna stay in TypeShed for a long while, and are definitely not 100% correct (but better than anything else you'll find out there)

Since #1774 there's also documentation being published to the GitHub pages.
